# SPDX-FileCopyrightText: 2021 Changgyoo Park <wvwwvwwv@me.com>
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "tss"
version = "0.1.0"
authors = ["wvwwvwwv <wvwwvwwv@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-epoch = "^0.9.3"
crossbeam-utils = "^0.8.3"
scc = "^0.4.14"

[workspace]
members = [".", "tests"]