# SPDX-FileCopyrightText: 2023 Changgyoo Park <wvwwvwwv@me.com>
#
# SPDX-License-Identifier: Apache-2.0

dev_comments = true

[Hunspell]
extra_dictionaries = [ "glossary.txt" ]
search_dirs = [ "." ]
use_builtin = true
