# SPDX-FileCopyrightText: 2023 Changgyoo Park <wvwwvwwv@me.com>
#
# SPDX-License-Identifier: Apache-2.0

dev_comments = true

[Hunspell]
extra_dictionaries = ["/Users/i064499/transactional-storage-framework/.config/glossary.txt"]
use_builtin = true
