# SPDX-FileCopyrightText: 2021 Changgyoo Park <wvwwvwwv@me.com>
#
# SPDX-License-Identifier: Apache-2.0

name: TSS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1.1
    - name: Debug - Build
      run: cargo build --verbose
    - name: Debug - Run tests
      run: cargo test --verbose
    - name: Release - Build
      run: cargo build --release --verbose
    - name: Release - Run tests
      run: cargo test --release --verbose
    - name: Document - Generate documentation
      run: cargo doc

